name: Check branch for PR

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR branch
        run: |
          echo "The source branch for this PR is: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Warning: This PR is from the '${{ github.head_ref }}' branch. Please ensure this is intended."
            exit 1  # 失敗ステータスを返してPRをマージ不可にする
          else
            echo "This PR is from the correct branch (develop)."
          fi