name: Run build
on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Run builds for Windows, Mac
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
        unityVersion: ['6000.0.31f1']
        include:
          - targetPlatform: StandaloneWindows64
            runsOn: windows-latest
            modules: windows-il2cpp
          - targetPlatform: StandaloneOSX
            runsOn: macos-latest
            modules: mac-il2cpp
    runs-on: ${{ matrix.runsOn }}
    steps:
      - name: Check out my unity project.
        uses: actions/checkout@v4.2.2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4.2.0
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run the build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      - name: Upload the Build for ${{ matrix.targetPlatform }}
        if: matrix.targetPlatform == 'StandaloneOSX'
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ steps.vars.outputs.sha_short }}
          path: build

      - name: バージョンを読み取る
        id: get_version
        run: |
          VERSION=$(cat build/StandaloneWindows64/version.txt)
          echo "app_version=$VERSION" >> $GITHUB_ENV

      - name: setup.issのMyAppVersionを更新する
        run: |
          sed -i 's/#define MyAppVersion ".*"/#define MyAppVersion "'$VERSION'"/' setup.iss

      - name: Set up Inno Setup
        if: matrix.targetPlatform == 'StandaloneWindows64'
        uses: Minionguyjpro/Inno-Setup-Action@v1.0.0
        with:
          path: 'setup.iss'

      - name: Upload Installer
        if: matrix.targetPlatform == 'StandaloneWindows64'
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Installer-${{ env.app_version }}
          path: "build/uDesktopMascot_${{ env.app_version }}.exe"
