name: Unity Test CI

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Unity Edit Mode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Cache Library
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          unityVersion: '6000.0.31f1'  # プロジェクトの Unity バージョンに合わせてください
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: './artifacts'

      - name: Upload Test Results
        uses: actions/upload-artifact@v4.6.0
        with:
          name: TestResults
          path: "**/TestResults/*.xml"