name: Translate README

on:
  pull_request:
    branches:
      - develop
    paths:
      - README.md

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: Install OpenAI library
      run: pip install openai
    
    - name: confirm library installation
      run: pip list

    - name: Run translation script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/scripts/translate_readme.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # 変更をステージしてコミット
        git add README_EN.md README_CN.md
        if git commit -m "Update translations"; then
          echo "Changes committed successfully."
          git push origin HEAD:${{ github.head_ref }}  # 現在のHEADをPRブランチ名にプッシュ
        else
          echo "No changes to commit"
        fi